// JavaScript Document

var aData = {
	headerMenu:{
		title:["小米手机","红米","平板 笔记本","电视","盒子 影音","路由器","智能硬件","服务","社区"],
		name:"小米Max",
		price:"1299元起",
		image:[
			"images/index_drop_prod1.jpg",
			"images/index_drop_red1.jpg",
			"images/index_drop_pad1.jpg",
			"images/index_drop_tv1.jpg",
			"images/index_drop_box1.jpg",
			"images/index_drop_router1.jpg",
			"images/index_drop_hard1.jpg",
			"images/index_drop_prod1.jpg",
			"images/index_drop_red1.jpg",
		]
	},
	headerRight:{
		search:{
			name:[
				"小米6","红米Note 4X","小米Mix",
				"小米Mix2","小米手机5c","小米手环",
				"小米盒子","小米路由器","小米充电宝",
			],
			piece:[
				"约有11件","约有7件","约有1件",
				"约有3件","约有3件","约有6件",
				"约有19件","约有7件","约有8件",
			]
		}
	},
	starSingleProduct:{
		title:["左","右"],
		name:"小米电视3S 43英寸",
		desc:"4GB内存+128GB闪存，陶瓷版",
		price:"1499元",
		classes:[
			"hvr-curl-bottom-left",
			"hvr-curl-bottom-right",
			"hvr-curl-top-left",
			"hvr-curl-top-right",
			"hvr-curl-bottom-left",
		],
		image:[
			"images/single/single1.png",
			"images/single/single2.png",
			"images/single/single3.png",
			"images/single/single4.png",
			"images/single/single5.jpg",
			"images/single/single6.png",
			"images/single/single7.png",
			"images/single/single8.png",
			"images/single/single9.jpg",
			"images/single/single10.png",
		]
	},
	slider:{
		image:[
			"images/index_slider_pic1.jpg",
			"images/index_slider_pic2.jpg",
			"images/index_slider_pic3.jpg",
			"images/index_slider_pic4.jpg",
			"images/index_slider_pic5.jpg",
		]
	},
	intelligent:{
		title:"智能硬件",
		name:"小米路由器3",
		price:"149元",
		desc:"四天线设计，更安全更稳定",
		status:["免邮件","有赠品"],
		classes:[
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
		],
		image:[
			"images/znyj/znyj1.jpg",
			"images/znyj/znyj2.jpg",
			"images/znyj/znyj3.jpg",
			"images/znyj/znyj4.jpg",
		]
	},
	match:{
		title:["搭配","配件"],
		name:"小米路由器3",
		price:"149元",
		cmt:"18.7万人评价",
		contents:{
			dapei:["热门","耳机音箱","电源","电池存储卡"],
			peijian:["热门","保护膜","贴膜","其他配件"]
		},
		evaluate:"音质非常好，很震撼！！美美美！",
		status:["免邮件","有赠品"],
		classes:[
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
		],
		image:[
			"images/dp/dp1.jpg",
			"images/dp/dp2.jpg",
			"images/dp/dp3.jpg",
			"images/dp/dp4.jpg",
			"images/dp/dp5.jpg",
			"images/dp/dp6.jpg",
			"images/dp/dp7.jpg",
			"images/dp/dp8.jpg",
			"images/dp/dp9.jpg",
			"images/dp/dp10.jpg",
			"images/dp/dp11.jpg",
			"images/dp/dp12.jpg",
			"images/dp/dp13.jpg",
			"images/dp/dp14.jpg",
		]
	},
	surrounding:{
		title:"周边",
		contents:["热门","服装","米兔","生活周边","箱包"],
		status:["免邮件","有赠品"],
		name:"小米路由器3",
		price:"149元",
		desc:"四天线设计，更安全更稳定",
		introL:{
			name:"小米小钢炮",
			price:"79元"
		},
		classes:[
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
		],
		image:[
			"images/zb/zb1.jpg",
			"images/zb/zb2.jpg",
			"images/zb/zb3.jpg",
			"images/zb/zb4.jpg",
			"images/zb/zb5.jpg",
			"images/zb/zb6.jpg",
			"images/zb/zb7.jpg",
			"images/zb/zb0.jpg",
		]
	},
	recommend:{
		title:["左","右"],
		name:"小米路由器3",
		cmt:"9000人好评",
		price:"149元",
		classes:[
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
		],
		image:[
			"images/wntj/wntj1.jpg",
			"images/wntj/wntj2.jpg",
			"images/wntj/wntj3.jpg",
			"images/wntj/wntj4.jpg",
			"images/wntj/wntj5.jpg",
			"images/wntj/wntj6.jpg",
			"images/wntj/wntj7.jpg",
			"images/wntj/wntj8.jpg",
			"images/wntj/wntj9.jpg",
			"images/wntj/wntj10.jpg",
		]
	},
	comment:{
		name:["小米净水器","小米Max2","小米路由器","小米自拍杆"],
		from:["来自于 taurus1992 的评价"],
		price:["699元"],
		cmt:[
			"自拍是一种病！拍起来真要命！蓝牙连接，比起插线的，简直提升了不少逼格～喜欢的蓝色～美哒哒～～",
			"样子好可爱，特别是转来转去时很有趣。让它休眠时它就会把头转过去背对着你了，唤醒它又会自动转回来。",
			"非常好用，孩子使用防止沉迷于电话影响学习。做工很好，定位基本准确，通话清晰。如果加入时间显示就更完美",
			"超级喜欢！小巧玲珑！音质完美！不知道为什么！只要是小米出的东西我都喜欢！那倒是因为那一句？？",
		],
		image:[
			"images/rpcp/rpcp1.jpg",
			"images/rpcp/rpcp2.jpg",
			"images/rpcp/rpcp3.jpg",
			"images/rpcp/rpcp4.jpg",
		]
	},
	content:{
		type:["图书","MIUI主题","游戏","应用"],
		classes:[
			"orange",
			"green",
			"red",
			"blue",
		],
		name:[
			"哈利·波特与被诅咒的孩子",
			"夏日狂想",
			"哈利波特与魔法石",
			"2017金米奖",
		],
		desc:[
			"“哈利·波特”第八个故事中文版震撼来袭！特别彩排版剧本！",
			"官方主题新画风，原来你是这样的小清新！",
			"免费下载海量的手机游戏天天都有现金福利赠送",
			"最优秀的应用和游戏",
		],
		classes:[
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
			"hvr-curl-top-left",
		],
		image:[
			"images/content/content1.png",
			"images/content/content2.jpg",
			"images/content/content3.png",
			"images/content/content4.png",
		]
	},
	video:{
		name:[
			"小米6外观设计视频",
			"听雷总讲述小米7年工艺探索之路",
			"小米电视4 外观设计视频",
			"4.9mm极超薄电视的诞生揭秘",
		],
		desc:[
			"震惊！小米6竟然如此之美",
			"小米6，7年工艺探索的巅峰之作",
			"美哭了！史上最美的小米电视",
			"小米电视工程师讲述极致之作的背后故事",
		],
		video:[
			"images/video/video1.jpg",
			"images/video/video2.jpg",
			"images/video/video3.jpg",
			"images/video/video4.jpg",
		],
	},
}
